import { ProductI } from "@/interfaces";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import FilterProducts from "@/components/FilterProducts";

async function fetchProducts(
  gender?: string,
  search?: string
): Promise<ProductI[] | undefined> {
  try {
    const url = new URL("http://localhost:5001/products");

    if (gender) url.searchParams.append("gender_like", gender);
    if (search) url.searchParams.append("q", search);

    const res = await fetch(url.toString());
    const data = await res.json();

    return data;
  } catch (error) {
    console.error(error);
  }
}
export default async function Shop({
  searchParams,
}: {
  searchParams: Promise<{ gender?: string; q?: string }>;
}) {
  const { gender, q } = await searchParams;
  const filteredProducts = await fetchProducts(gender, q);
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg0 m-t-23 p-b-140">
        <div className="container">
          <FilterProducts />

          <div className="row isotope-grid">
            {filteredProducts && filteredProducts.length > 0 ? (
              filteredProducts.map((product) => (
                <div
                  key={product.id}
                  className="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item"
                >
                  <div className="block2">
                    <div className="block2-pic hov-img0">
                      <Image
                        src={product.img}
                        alt={product.title}
                        width={300}
                        height={400}
                      />
                      <Link
                        href={`/shop/${product.id}`}
                        className="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04"
                      >
                        View Details
                      </Link>
                    </div>
                    <div className="block2-txt flex-w flex-t p-t-14">
                      <div className="block2-txt-child1 flex-col-l">
                        <Link
                          href={`/shop/${product.id}`}
                          className="stext-104 cl4 hov-cl1 trans-04"
                        >
                          {product.title}
                        </Link>
                        <span className="stext-105 cl3">{product.price}</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))
            ) : (
              <p className="text-center w-full">There are no results.</p>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
