import BlogItem from "@/components/BlogItem";
import PageTitle from "@/components/PageTitle";
import ProductItem from "@/components/ProductItem";
import { BlogI, ProductI } from "@/interfaces";
import type { NextPage } from "next";
import Head from "next/head";

async function fetchData(query: string): Promise<{
  BlogData: BlogI[];
  ProductData: ProductI[];
}> {
  const BlogRes = await fetch(`http://localhost:5001/blogs?&q=${query}`);
  const BlogData: BlogI[] = await BlogRes.json();

  const ProductRes = await fetch(`http://localhost:5001/products?&q=${query}`);
  const ProductData: ProductI[] = await ProductRes.json();

  return { BlogData, ProductData };
}

export default async function Search({
  searchParams,
}: {
  searchParams: { q: string };
}) {
  const { q } = searchParams;

  const { BlogData, ProductData } = await fetchData(q);

  const hasBlogs = BlogData.length > 0;
  const hasProducts = ProductData.length > 0;

  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={"Search"} />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          {hasBlogs && (
            <>
              <h2 className="mb-5">Blogs</h2>
              <div className="row isotope-grid">
                <div className="col-4">
                  {BlogData.map((blog) => (
                    <BlogItem key={blog.id} {...blog} />
                  ))}
                </div>
              </div>
            </>
          )}

          {hasProducts && (
            <>
              <h2 className="mb-5">Products</h2>
              <div className="row isotope-grid">
                {ProductData.map((product) => (
                  <ProductItem key={product.id} {...product} />
                ))}
              </div>
            </>
          )}

          {!hasBlogs && !hasProducts && (
            <div className="text-center mt-5">
              <h3>No results found for {q}</h3>
              <p>Try searching for something else.</p>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
